### ISSUE TITLE
Menu isn't hidden on polymer 1.6

### ISSUE THREAD

**Issue by yonathan9669** [pomber/paper-fab-speed-dial#1]
Hey, I like your elements and I'll use it in a project but you need to include this in your style now.

`.container ::content > .dropdown-content[hidden] {
        display: none;
      }`

Polymer stop hide elements with the hidden attr so you have to include it now in your style.

Please do the update because I manually fixed it for now, but I would like to know it's working for everyone. Cheers =D.

**Comment by pomber** [comment]
Hi @yonathan9669, thanks a lot for the feedback.  
I just tried the element with Polymer 1.7.1 and `[hidden]` is still working.  
Which browser are you using? Could you share more information to help me reproduce it?

**Comment by yonathan9669** [comment]
Hi @pomber, here are my bower dependences. you should be able to reproduce it with them because every browser (desktop or mobile) with the chromium engine (chrome, canary, opera, etc.) generate the same issue. I just delete my bower_components and reinstall them as -f to see if it was something about them but I'm still getting the issue. I include the style rule and works perfectly everywhere.

> "dependencies": {
    "app-layout": "PolymerElements/app-layout#^0.10.0",
    "app-route": "PolymerElements/app-route#^0.9.0",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#^1.0.0",
    "iron-icon": "PolymerElements/iron-icon#^1.0.0",
    "iron-iconset-svg": "PolymerElements/iron-iconset-svg#^1.0.0",
    "iron-localstorage": "PolymerElements/iron-localstorage#^1.0.0",
    "iron-media-query": "PolymerElements/iron-media-query#^1.0.0",
    "iron-pages": "PolymerElements/iron-pages#^1.0.0",
    "iron-selector": "PolymerElements/iron-selector#^1.0.0",
    "paper-icon-button": "PolymerElements/paper-icon-button#~1.1.0",
    "iron-ajax": "PolymerElements/iron-ajax#^1.4.3",
    "polymer": "Polymer/polymer#^1.6.0",
    "paper-menu": "PolymerElements/paper-menu#^1.2.2",
    "iron-icons": "PolymerElements/iron-icons#^1.2.0",
    "google-map": "GoogleWebComponents/google-map#^1.2.0",
    "google-signin": "GoogleWebComponents/google-signin#^1.3.7",
    "vaadin-grid": "vaadin/vaadin-grid#^1.2.1",
    "vaadin-combo-box": "vaadin/vaadin-combo-box#^1.2.0",
    "paper-fab-speed-dial": "pomber/paper-fab-speed-dial#^0.5.3",
    "paper-fab": "PolymerElements/paper-fab#^1.2.1"
  },

And hey should be really useful if you include something like this.

`.container{
                @apply(--paper-fab-speed-dial-mixin); !important;
            }`

so the element could be more customisable.

BTW It's the browser who stop hidden the elements not polymer, my bad.
Cheers =D

**Comment by pomber** [comment]
Oh, looks like the problem is using it inside of the `app-drawer-layout`. It overrides `display` to `flex`.

**Comment by pomber** [comment]
Fixed in `v0.5.4`. Thanks!

**Comment by yonathan9669** [comment]
awesome =D thanks...

if you don't mind this will really be helpful too

`.container{ @apply(--paper-fab-speed-dial); !important; }`

So anyone could decide where to put it and not just on the lower buttom.
Cheers

**Comment by pomber** [comment]
Feel free to submit any improvement as a pull request :)
