### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Philanatidae** [pomber/paper-fab-speed-dial#3]
I noticed there was no license attached to this project... I would like to use this in an app I am developing, and my remarks to how well this works! Exactly what I'm looking for.
I suggest the [BSD 3-Clause License (Revised)](https://www.tldrlegal.com/l/bsd3), as it is the license that Polymer itself is licensed under. Up to the project owner, of course.

**EDIT:** I just noticed that bower.json says that this library is under the MIT license. Is this correct?

**Comment by pomber** [comment]
Yes, license is in bower.json. Do you think we also need a license file? (I
know nothing about licenses)

**Comment by Philanatidae** [comment]
It would be extremely useful for others wishing to use this element in their projects if you had a license file. Plus, I believe that the MIT requires it, though I'm not 100% sure. I would include it to prevent confusion in the future.

https://opensource.org/licenses/MIT

I am not a lawyer.

**Comment by pomber** [comment]
Thanks, I'll add it later. You may also submit it as a pull request if you
need it sooner.
